# Generated by Django 4.2.13 on 2025-11-02 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentrequest',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_requests', to='photos.photo'),
        ),
        migrations.AddField(
            model_name='consentrequest',
            name='requested_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_requests_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
