# Generated by Django 4.2.13 on 2025-10-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='encoding_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('NO_FACE', 'No Face Found'), ('ERROR', 'Error')], default='PENDING', help_text='Status of face encoding extraction', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='face_encoding',
            field=models.JSONField(blank=True, help_text='128-dimensional face encoding vector', null=True),
        ),
    ]
